#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

#------------------------------- hemodynamic4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# Get application name from directory
application=icoFsiFoam

./Allclean
cd fluid
surfaceFeatureEdges aorta.stl aorta.fms
#cartesianMesh
tetMesh 
autoPatch 55 -overwrite
createPatch -overwrite
transformPoints -scale '(0.001 0.001 0.001)'
checkMesh



cd ../solid
extrudeMesh
autoPatch 70 -overwrite
createPatch -overwrite
checkMesh
